apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: rails-kaniko-run
spec:
  pipelineRef:
    name: rails-kaniko-pipeline
  params:
    - name: url
      value: https://github.com/AslinDhurai/rails-k8s-gitops.git
    - name: revision
      value: main
    - name: IMAGE
      value: docker.io/aslindhurai/rails-app:latest
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-workspace-pvc
    - name: basic-auth
      secret:
        secretName: github-secret

