apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-kaniko-pipeline
spec:
  params:
    - name: url
    - name: revision
      default: main
    - name: IMAGE
  workspaces:
    - name: shared-workspace
    - name: basic-auth
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: basic-auth
          workspace: basic-auth
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)

    - name: build-and-push
      taskRef:
        name: build-and-push-kaniko
      runAfter:
        - clone
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: output
          workspace: shared-workspace

