apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rails-kaniko-pipeline
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "main"
    - name: IMAGE
      type: string
  workspaces:
    - name: shared-workspace
    - name: basic-auth
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: username
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: password
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: basic-auth
          workspace: basic-auth

    - name: build-and-push
      runAfter:
        - clone
      taskRef:
        name: kaniko-task
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace

