apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  clusterIP: None  # Important for StatefulSet to allow stable DNS like postgres-0.postgres

