apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/AslinDhurai/rails-k8s-gitops.git
  username: AslinDhurai
  password: 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

