version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate && rails s -b 0.0.0.0"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:

